### ISSUE TITLE
Invitation to contribute to the upstream minitar project.

### ISSUE THREAD

**Issue by halostatue** [atoulme/minitar#3]
I see you have forked the archive-tar-minitar project a few years ago and have added changes that were never contributed back to the original project.

I invite you to submit those as pull requests to the original project source at [halostatue/minitar](https://github.com/halostatue/minitar), because I’m going to be pushing a new version soon with a modernization of the codebase.

**Comment by atoulme** [comment]
Austin, sorry for the long long delay. I gave you ownership over `minitar` just now.

**Comment by halostatue** [comment]
Thanks! I will try to get all of your changes pulled into minitar and also, because you did this work when I had not done anything with minitar for a while, give you commit-bit to the upstream project.

**Comment by halostatue** [comment]
I can’t promise that I’ll get a new release out before the end of January, but I will plan a new release by the end of February.

**Comment by atoulme** [comment]
Thanks. I am honored by your gesture. I will try to push changes to your repo this year!
